# Generated by Django 5.0.6 on 2024-07-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_person_address_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.IntegerField(),
        ),
    ]
