# Generated by Django 5.0.6 on 2024-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_person_gender_alter_person_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
